name: Update Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  Update-Data-Job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run updatedata
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: commit-data
        with:
          commit_message: Update data
      - name: "Run if changes have been detected"
        if: steps.commit-data.outputs.changes_detected == 'true'
        run: echo "Changes!"
      - name: "Run if no changes have been detected"
        if: steps.commit-data.outputs.changes_detected == 'false'
        run: echo "No Changes!"
